

export const FETCH_BOOKINGS_REQUEST = 'FETCH_BOOKINGS_REQUEST'
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS'
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE'

export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE'

