

export const FETCH_MEETINGROOMS_REQUEST = 'FETCH_MEETINGROOMS_REQUEST'
export const FETCH_MEETINGROOMS_SUCCESS = 'FETCH_MEETINGROOMS_SUCCESS'
export const FETCH_MEETINGROOMS_FAILURE = 'FETCH_MEETINGROOMS_FAILURE'
